### ISSUE TITLE
New protocol HTPP? 👀 

### ISSUE THREAD

**Issue by Opwi** [shaadx-coding/infrastructure-shaadx#2]
Hello,

It seems that you create a new back-end protocol. Can you tell me more?

Have a nice day.

https://github.com/shaadx-coding/infrastructure-shaadx/blob/ae9ea5fab8726d460ed1e28d5229dc34b4a58758/k8s/manifests/ouestlinfra/ingress.yml#L9

**Comment by shaadx-coding** [comment]
Hi,

My bad it seem to be a typo on my part.

Thank you and have a nice day.

**Comment by shaadx-coding** [comment]
Resolved in fe35033
